version: "3.7"

services:
  backend:
    build:      
      context: .
      dockerfile: Dockerfile
    image: "backend:${TAG}"
    container_name: container-back    
    env_file:
      - ./SECRETS_DJANGO.env    
    ports:
      - "8000:8000"