version: '3.7'

services:
  frontend:    
    build:      
      context: ./frontend/
      dockerfile: Dockerfile
    image: "frontend:${TAG}"
    container_name: container-frontend
    restart: always    
    ports:
      - "3000:3000"
    networks:
      - WebApp
  backend:
    build:      
      context: ./backend/
      dockerfile: Dockerfile
    image: "backend:${TAG}"
    container_name: container-back    
    env_file:
      - ./SECRETS_DJANGO.env    
    ports:
      - "8000:8000"
    networks:
      - WebApp
      
networks:
  WebApp:
    name: networks_WebApp
    driver: bridge