name: deployment on docker-hub

on:
  push:
    paths:
    - 'Nginx/WWW'
    
jobs:
  deploy:
    runs-on: ubuntu-20.04
    name: deploy image to docker-hub
    steps:
      - name: Checkout code
        uses: actions/checkout@v3 

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          contexts: './Nginx'
          push: true  
          tags: ${{ secrets.DOCKERHUB_USERNAME }}:latest
