name: deployment on docker-hub

on:
  push:
    paths:
    - 'Nginx/WWW/*'
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    name: deploy image to docker-hub
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}           
      
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:Nginx"          
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/devops-interview:latest
